// LOCALHOST 
### get all recipes
GET http://localhost:8080/recipes

### Get single recipe by Id
GET http://localhost:8080/recipes/63cc041a1b1ea223f39615c1

### Create a recipe 
POST http://localhost:8080/recipes/ HTTP/1.1
content-type: application/json

  {
    "_id": "28469",                     
    "recipeName": "THE bouquet",             
    "recipeSize": "large",              
    "recipeCategory": "bridal bouquet",          
    "recipeContainer": "hand wrap",         
    "recipeIngredients": "2 dozen roses, floral wire, wide satin ribbon",
    "recipeInstructions": "Begin with five roses in one hand. Add a rose, then rotate the bunch in your hand slightly to add the next rose. Press the rose tightly up against the last one. Keep rotating as you add each rose one at a time. Always maintain a tight grip on the bunch so they don't shift around as you add a rose. The roses should appear to spiral from the center to the outer edges of the bouquet. Wrap the stems tightly with floral wire. Start at about 3 inches below the base of the blooms and wrap around the stems at least 10 times without overlapping, the wrapped area should be slightly less than four inches wide. Cover the wire completely with 4-inch satin ribbon. Secure the ribbon with hot glue",
    "recipeNotes": "This bouquet is extremely popular with brides."
  }
  
### Update a recipe 
PUT http://localhost:8080/recipes/63d009485248b2af338e1f6c HTTP/1.1
content-type: application/json

  {
    "_id": "28469",                     
    "recipeName": "THE bouquet",             
    "recipeSize": "large",              
    "recipeCategory": "bridal bouquet",          
    "recipeContainer": "hand wrap",         
    "recipeIngredients": "2 dozen roses, floral wire, wide satin ribbon",
    "recipeInstructions": "Begin with five roses in one hand. Add a rose, then rotate the bunch in your hand slightly to add the next rose. Press the rose tightly up against the last one. Keep rotating as you add each rose one at a time. Always maintain a tight grip on the bunch so they don't shift around as you add a rose. The roses should appear to spiral from the center to the outer edges of the bouquet. Wrap the stems tightly with floral wire. Start at about 5 inches below the base of the blooms, moving away from the base toward the ends of the stems, wrapping around the stems at least 12 times without overlapping. The wrapped area should be slightly less than four inches wide. Cover the wire completely with 5-inch (or wider) satin ribbon. Secure the ribbon with hot glue. Trim the stems at about 9 inches below the bottom of the ribbon.",
    "recipeNotes": "This bouquet is extremely popular with brides."
  }

### Delete a recipe
DELETE http://localhost:8080/recipes/63d009485248b2af338e1f6c


// PRODUCTION Deploy 

### Get all recipes
GET https://cse341-w2.onrender.com/recipes/ 

### Get a single recipe by Id
GET https://cse341-w2.onrender.com/recipes/63de262c882fc17d74f6d5e7 

### Create a recipe 
POST https://cse341-w2.onrender.com/recipes/ HTTP/1.1
content-type: application/json

  {
    "_id": "28469",                     
    "recipeName": "THE bouquet",             
    "recipeSize": "large",              
    "recipeCategory": "bridal bouquet",          
    "recipeContainer": "hand wrap",         
    "recipeIngredients": "2 dozen roses, floral wire, wide satin ribbon",
    "recipeInstructions": "Begin with five roses in one hand. Add a rose, then rotate the bunch in your hand slightly to add the next rose. Press the rose tightly up against the last one. Keep rotating as you add each rose one at a time. Always maintain a tight grip on the bunch so they don't shift around as you add a rose. The roses should appear to spiral from the center to the outer edges of the bouquet. Wrap the stems tightly with floral wire. Start at about 3 inches below the base of the blooms and wrap around the stems at least 10 times without overlapping, the wrapped area should be slightly less than four inches wide. Cover the wire completely with 4-inch satin ribbon. Secure the ribbon with hot glue",
    "recipeNotes": "This bouquet is extremely popular with brides."
  }
  
### Update a recipe 
PUT https://cse341-w2.onrender.com/recipes/63deab1a12dbce785846d80f HTTP/1.1
content-type: application/json

  {
    "_id": "28469",                     
    "recipeName": "THE bouquet",             
    "recipeSize": "large",              
    "recipeCategory": "bridal bouquet",          
    "recipeContainer": "hand wrap",         
    "recipeIngredients": "2 dozen roses, floral wire, wide satin ribbon",
    "recipeInstructions": "Begin with five roses in one hand. Add a rose, then rotate the bunch in your hand slightly to add the next rose. Press the rose tightly up against the last one. Keep rotating as you add each rose one at a time. Always maintain a tight grip on the bunch so they don't shift around as you add a rose. The roses should appear to spiral from the center to the outer edges of the bouquet. Wrap the stems tightly with floral wire. Start at about 5 inches below the base of the blooms, moving away from the base toward the ends of the stems, wrapping around the stems at least 12 times without overlapping. The wrapped area should be slightly less than four inches wide. Cover the wire completely with 5-inch (or wider) satin ribbon. Secure the ribbon with hot glue. Trim the stems at about 9 inches below the bottom of the ribbon.",
    "recipeNotes": "This bouquet is extremely popular with brides."
  }

### Delete a recipe
DELETE https://cse341-w2.onrender.com/recipes/63deab1a12dbce785846d80f