// LOCALHOST 
### get all users
GET http://localhost:8080/user

### Get single user by username
GET http://localhost:8080/user/JoveyJoJo

### Create a user 
POST http://localhost:8080/user/ HTTP/1.1
content-type: application/json

{           
  "username": "JoveyJoJo",
  "password": "P@ssw0rd7890",
  "displayName": "Jovey",
  "email": "joveyjojo@test.com"
}

### Update a user 
PUT http://localhost:8080/user/JoveyJoJo HTTP/1.1
content-type: application/json

{           
  "username": "JoveyJoJo",
  "password": "P@ssw0rd7890",
  "displayName": "JoveyJoJo",
  "email": "joveyjojo@test.com"
}

### Delete a user
DELETE http://localhost:8080/user/JoveyJoJo HTTP/1.1


// PRODUCTION Deploy 

### Get all users
GET https://cse341-w2.onrender.com/user/ 

### Get a single user by username
GET https://cse341-w2.onrender.com/user/username 

### Create a user
POST https://cse341-w2.onrender.com/user/ HTTP/1.1
content-type: application/json

{           
  "username": "Rose",                           
  "botanicalFamily": "Rosaceae",           
  "botanicalGenus": "Rosa",            
}
  
### Update a user
PUT https://cse341-w2.onrender.com/user/username HTTP/1.1
content-type: application/json

{          
  "username": "Rose",                            
  "botanicalFamily": "Rosaceae",           
  "botanicalGenus": "Rosa"            
}

### Delete a user
DELETE https://cse341-w2.onrender.com/user/username HTTP/1.1