FLOWERS

definitions: 
  _id: 
    type: string
        commonName: 
          type: string
        botanicalName: 
          type: string
        botanicalFamily: 
          type: string
        botanicalGenus: 
          type: string
        availability: 
          type: array
          items: 
            type: object
            properties: 
              where: 
                type: string
              when: 
                type: string
        vaseLife: 
          type: string
        description: 
          type: array
          items: 
            type: object
            properties: 
              notes: 
                type: string
              stemLength: 
                type: string
        colorRange: 
          type: string
        florist: 
          type: array
          items: 
            type: object
            properties: 
              conditioning: 
                type: string
              storage: 
                type: string
              display: 
                type: string
              stemType: 
                type: string
        homeCare: 
          type: string


RECIPES
  definitions: 
    recipes: 
      type: object
      properties: 
        _id: 
          type: string
        recipeName: 
          type: string
        recipeSize: 
          type: string
        recipeCategory: 
          type: string
        recipeContainer: 
          type: string
        recipeIngredients: 
          type: array
          items: 
            type: object
            properties: 
              foliage: 
                type: array
                items: 
                  type: object
                  properties: 
                    foliage1: 
                      type: string
                    foliage2: 
                      type: string
                    foliage3: 
                      type: string
              focusFlowers: 
                type: array
                items: 
                  type: object
                  properties: 
                    focusFlower1: 
                      type: string
                    focusFlower2: 
                      type: string
                    focusFlower3: 
                      type: string
                    focusFlower4: 
                      type: string
                    focusFlower5: 
                      type: string
              fillerFlowers: 
                type: array
                items: 
                  type: object
                  properties: 
                    fillerFlower1: 
                      type: string
                    fillerFlower2: 
                      type: string
                    fillerFlower3: 
                      type: string
                    fillerFlower4: 
                      type: string
                    fillerFlower5: 
                      type: string
              accessories: 
                type: array
                items: 
                  type: object
                  properties: 
                    accessory1: 
                      type: string
                    accessory2: 
                      type: string
                    accessory3: 
                      type: string
                    accessory4: 
                      type: string
                    accessory5: 
                      type: string
        recipeInstructions: 
          type: array
          items: 
            type: object
            properties: 
              prep: 
                type: array
                items: 
                  type: object
                  properties: 
                    prepContainer: 
                      type: string
                    prepFoliage: 
                      type: string
                    prepFlowers: 
                      type: string
                    prepAccessories: 
                      type: string
                    prepOther: 
                      type: string
              arrange: 
                type: array
                items: 
                  type: object
                  properties: 
                    arrFoliage: 
                      type: string
                    arrFocus: 
                      type: string
                    arrFiller: 
                      type: string
                    arrAccessories: 
                      type: string
        recipeNotes: 
          type: string
